### ISSUE TITLE
Disabling iframe causes uncaught type error

### ISSUE THREAD

**Issue by newswim** [Shopify/buy-button-js#291]
`Uncaught TypeError: Cannot read property 'el' of null`

Here's my code snippet:

```js
      songIds.forEach((id) => {
          ui.createComponent('product', {
            id: id,
            options: {
                product: {
                    buttonDestination: 'modal',
                    iframe: false
                },
            },
          });
      })
```

`resizeY` appears to get called even when iframe is disabled.

**Comment by tessalt** [comment]
@newswim great catch, I have a pull request to fix this https://github.com/Shopify/buy-button-js/pull/292
