### ISSUE TITLE
"Add to Cart" Button Adding 2x Items at a Time

### ISSUE THREAD

**Issue by milsanore** [Shopify/buy-button-js#349]
Clicking the "Add to Cart" button adds 2x items to the cart, even when the button quantity is displayed and set to 1.

Note: If I set the button quantity to 45 the cart quantity => 406 !!!

**Comment by michelleyschen** [comment]
@milsanore what is the options you use for re-creating this issue?

**Comment by bgold0** [comment]
Have you been updating the quantity of a product via `addVariantToCart`? If so I've found that you need to set `product.model.selectedQuantity = 1;` before you do anything.

**Comment by rebeccajfriedman** [comment]
Closing as we've haven't encountered any additional reports of this.
