### ISSUE TITLE
Possibility of modifying shown price 

### ISSUE THREAD

**Issue by sniepoort** [Shopify/buy-button-js#362]
Our products on our main website have an input price without taxes, and are told to calculate taxes on checkout. However, our templates actually calculate the price with taxes, which are shown to the customer on viewing the products. This is due to selling in different countries, where some should not be charged taxes. 

So, the problem arises when we don't really have control over a price output, like with the buy button. Granted, taxes will be calculated on checkout, but they should also as part of the product. 
Any suggestions?

**Comment by michelleyschen** [comment]
hi @sniepoort,
have you tried using the shopify taxes setting described (here)[https://help.shopify.com/manual/taxes] to included all taxes as part of your product price?

**Comment by sniepoort** [comment]
Yes. Normally, if just selling in one country (Denmark), we would have taxes included in the price, and then shopify would be able to tell how much of that price is tax (25%) when checking out. However, as described, when we sell to for example Norway, we would not charge taxes on their purchase. Therefore we cannot have taxes included in the price. But usually taxes are included when viewing products on webshops in Denmark, so therefore we have added custom code to our theme to modify the shown price, so it shows the price with 25%. 

So unfortunately I don't see that we could do anything on our tax setup to solve this particular problem

**Comment by michelleyschen** [comment]
If I am understanding this correctly, what I would do is in the tax setting, check `All taxes are included in my prices` with tax rates setting as 25% for Denmarkm and 0% on Norway. Then the appropriate tax calculation will show up on the checkout page beside the total:
ex.
<img width="1232" alt="screen shot 2017-02-27 at 2 00 23 pm" src="https://cloud.githubusercontent.com/assets/1610169/23376353/c5393ce0-fcf9-11e6-85b5-7ebe8af11d65.png">

**Comment by sniepoort** [comment]
You would think so, but when tried that, the price for Norway just remained the same. I.e., it didn't "subtract" 25% from the price

**Comment by michelleyschen** [comment]
would you be able to share some more information / screen shot about what you are experiencing?
just because I don't think I fully understand what you are trying to accomplish. If you don't want to share this publicly you can email us at buybutton@shopify.com

**Comment by michelleyschen** [comment]
Ok, I think I understand what you are trying to accomplish now.
What you would do is set a customized template for your `product` component and write a customized view data getter.

ex.
```
options: {
    product: {
      viewData: {
        modifyPrice: function () {
          // your price calculation
          return modifyPrice;
        },
      },
      templates: {
        price: '{{data.modifyPrice}}',
      },
```

**Comment by sniepoort** [comment]
Aha, I didn't notice that part of the docs. I'll give that a try!
Do you know if it's available for all models? As in, would I be able to do it both for products, product modals, and the cart?

**Comment by sniepoort** [comment]
I'm not really understanding your example. The modifyPrice functions needs some sort of data to calculate and return. As far as I can see, no parameters are passed on to that function?
I.e. 
``` javascript
"templates": {
  "price": '{{data.modifyPrice}}',
},
"viewData": {
  "modifyPrice": function (price) {
    console.log(price)
    return price;
  },
`},`
```
If you log the price, you just get undefined

**Comment by michelleyschen** [comment]
the method in viewData is essentially a getter in the context of the component. 
It has no parameters but if you use `this`, you will get back the instance of the component itself (in this case `product`). And yes, you can do this with all the components.

ie. 
```
"viewData": {
  "modifyPrice": function () {
    console.log(this)
  },
},
```

**Comment by sniepoort** [comment]
Hi again,
Could you guide me on how to modify the cart? I can't quite see where to find what templates the cart uses
