### ISSUE TITLE
fill-mode forwards in flipIn animation causes Chrome rendering issues

### ISSUE THREAD

**Issue by AmeliaBR** [Shopify/buy-button-js#365]
In the shopping cart, the animations on the line items are causing the text to be rendered poorly in Chrome (on Windows):

![The price €139.00, displayed twice in dark blue. The top version is slightly blurry, so that it appears to be a thicker-weight font in a lighter color.](https://cloud.githubusercontent.com/assets/9876129/23584499/dc6e7de6-0120-11e7-8e93-37b82279afff.png)

The top version is the price in a line-item; the bottom version is the price in the sub-total.  The screenshots are from a lower-res screen, but the difference is also visible on a fairly good resolution laptop screen.

The problem seems to be entirely caused by freezing the element in animation mode (`animation-fill-mode: forwards`) after the 3D `flipIn` animation.  The fill mode does not appear to be necessary: the base style (without animation) are the same as the animation final state.  

You should be able to safely remove `forwards` from [the css](https://github.com/Shopify/buy-button-js/blob/6bb980eb5e5ae2aa3a8d184fa553c07b4b2cdaf7/src/styles/embeds/sass/components/cart.css#L92).

You can also safely remove the `to` block from the `flipIn` keyframes, and the `from` block from the `flipOut` keyframes, since they are the same as the un-animated element styles.

**Comment by rebeccajfriedman** [comment]
Closing as stale. Please reopen if problem persists.
