### ISSUE TITLE
Adding Custom Events to Toggle Button

### ISSUE THREAD

**Issue by AlcuinGuest** [Shopify/buy-button-js#366]
I know this isn't an issue, it's more of a cry for help. Nevertheless, I would sincerely appreciate your reply!

So I've embedded my product buy button into my site, and that works great. I can also add custom events to that buy button using this syntax: 
`"DOMEvents": {
				    'click button': function (event) {
				     	$('.darkOverlay').toggleClass('fadeIn');
						$('.darkOverlay').toggleClass('fadeOut');
				    }
				  },`

However, when i attempt to fire the same function on the cart toggle button (the one that opens/closes the cart), it does not work. I do not seem to be able to select the element, meaning I cannot fire any functions from it.

Any help would be hugely appreciated!

**Comment by tanema** [comment]
You should be able to use options that look like this to add an event to the toggle.
```
options = {
  toggle: {
    DOMEvents: {
      'click': function (evt, target) {
        // You will probably need to call ui.openCart() since 
        // this event overrides the default click event
      }
    }
  }
}
```

**Comment by tanema** [comment]
I closed this because I verified that you can use those options to call a function this way. You will also definitely need to use ui.openCart() to make sure that the cart still opens.
