### ISSUE TITLE
Create an option to customize which image size is used

### ISSUE THREAD

**Issue by AmeliaBR** [Shopify/buy-button-js#370]
It looks like the Buy Button code always uses the "large" image for product displays.  It would be nice if this was a customizable option, with options similar to [the image size parameters for the Liquid `img_url` filter](https://help.shopify.com/themes/liquid/filters/url-filters#img_url).

Ideally, you would also expose all the "standard size" URL variants in the `data` object, so that they could be used in custom templates.  For example, a template could use `<picture>` markup to generate automatically-responsive images.

**Comment by michelleyschen** [comment]
`buy-button-js` uses either `grande` or `large` depending on the layout or if the product width is set.

You can also change it using 
```
options: {
    "product": {
    "imageSize":"1024x1024"

**Comment by AmeliaBR** [comment]
Awesome!  

So, maybe this issue can instead be "Update docs to mention the imageSize customization parameter"?  I'm using a custom layout (no iframe, injecting the product listings into the web site), so the automatic calculation isn't enough.  And it didn't help that I was fighting with JPEG artifacts from Shopify's automatic image re-formatting (I'll know for next time: upload high quality JPEG files, not web-quality images!)

**Comment by timelytree** [comment]
Hey @michelleyschen or @AmeliaBR, I'm just getting started on trying to integrate `buy-button-js` into my own custom layout (also no iframe) and have run into the same difficulty of trying to pull a smaller image and was hoping either of you could help me out.

Here's a code snippet I'm using to pull products:

```javascript
shopClient.fetchQueryProducts({
  collection_id: 123456789,
  options: {
    "product": {
      "imageSize":"1024x1024"
    }
  }
})
```

It looks like the option to choose that specific image size isn't working and I assume I'm placing the `options` parameter in the wrong place in the query.

Can either of you point me in the right direction?

**Comment by michelleyschen** [comment]
@timelytree `shopClient.fetchQueryProducts` is part of the JS Buy SDK and not `buy-button-js`
please refer to this doc for JS Buy SDK usage http://shopify.github.io/js-buy-sdk/

**Comment by timelytree** [comment]
Ah I see! Thanks for the clarity :)

**Comment by bryanmlewis** [comment]
Hey @michelleyschen , I know this is over a year old, but I'm trying to get `buy-button-js` to deliver me images that are higher quality than src and srcLarge. I've tried the imageSize to no avail.

I am currently using a template for the imgWithCarousel (by default, the buy-button arrows are missing 'https://' in their source and don't show up), but I'm looking if there is a way to access the original size from within (like {{data.currentImage.srcOriginal}} instead of {{data.currentImage.srcLarge}} to get the unappended image uri

**Comment by michelleyschen** [comment]
@melissaluu would you know what to do here?

**Comment by bryanmlewis** [comment]
I've been trying to do some "afterRender" workaround where I just strip the _550x825 out of the image url, but I'm not sure if that works with modalproduct (or at least I haven't gotten that event working)

**Comment by melissaluu** [comment]
@bryanmlewis - at the moment, `buy-button-js` only provides the 2 image sizes via `src` and `srcLarge` and does not expose the "raw" image src without image dimensions.  Also, the `imageSize` option has been deprecated as of `v0.5.0`.
https://github.com/Shopify/buy-button-js/blob/ba89d7fa2f4944da7f388a9b6d632d764b376e5f/src/components/product.js#L111-L158

**Comment by bryanmlewis** [comment]
@melissaluu @michelleyschen Thank you for your quick responses— I didn't think there were any more image sizes to pull from, but I figured I would check!

**Comment by fabskills** [comment]
@melissaluu @michelleyschen  @bryanmlewis 

Hello there !
I'm really not an expert in javascipt, I need your help on the buy button, I just want the images of my collection do not lose in quality or resizing in the "modal" section when I click on the button to see more, it's all day that I looking for wich part of the code I need to edit ... can you help me ?

you can see the poor quality image on my website : ( when clicking on "voir plus" or "see more" )
https://intothefab.com/prints/



here is the code  :

<div id='collection-component-694fd53f1f2'></div>
<script type="text/javascript">
/*<![CDATA[*/

(function () {
  var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';
  if (window.ShopifyBuy) {
    if (window.ShopifyBuy.UI) {
      ShopifyBuyInit();
    } else {
      loadScript();
    }
  } else {
    loadScript();
  }

  function loadScript() {
    var script = document.createElement('script');
    script.async = true;
    script.src = scriptURL;
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
    script.onload = ShopifyBuyInit;
  }

  function ShopifyBuyInit() {
    var client = ShopifyBuy.buildClient({
      domain: 'digital-nomad-adventure.myshopify.com',
      apiKey: '87aef35ebb5c90a273cd0f95f12479db',
      appId: '6',
    });

    ShopifyBuy.UI.onReady(client).then(function (ui) {
      ui.createComponent('collection', {
        id: 43837587498,
        node: document.getElementById('collection-component-694fd53f1f2'),
        moneyFormat: '%E2%82%AC%7B%7Bamount_with_comma_separator%7D%7D',
        options: {
  "product": {
    "buttonDestination": "modal",
    "variantId": "all",
    "isButton": false,
    "contents": {
      "imgWithCarousel": false,
      "variantTitle": false,
      "options": false,
      "description": false,
      "buttonWithQuantity": false,
      "quantity": false
    },
    "text": {
      "button": "VOIR PRODUIT"
    },
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "calc(50% - 40px)",
          "margin-left": "40px",
          "margin-bottom": "50px"
        }
      },
      "button": {
        "background-color": "#363636",
        ":hover": {
          "background-color": "#313131"
        },
        ":focus": {
          "background-color": "#313131"
        }
      }
    }
  },
  "cart": {
    "contents": {
      "button": true
    },
    "text": {
      "title": "Panier",
      "total": "Total",
      "notice": "\nLes codes de livraison et de réduction sont ajoutés au checkout",
      "empty": "Votre panier est vide"
    },
    "styles": {
      "button": {
        "background-color": "#363636",
        ":hover": {
          "background-color": "#313131"
        },
        ":focus": {
          "background-color": "#313131"
        }
      },
      "footer": {
        "background-color": "#ffffff"
      }
    }
  },
  "modalProduct": {
    "contents": {
      "img": false,
      "imgWithCarousel": true,
      "variantTitle": false,
      "buttonWithQuantity": true,
      "button": false,
      "quantity": false
    },
    "text": {
      "button": "AJOUTER AU PANIER"
    },
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "100%",
          "margin-left": "0px",
          "margin-bottom": "0px"
        }
      },
      "button": {
        "background-color": "#363636",
        ":hover": {
          "background-color": "#313131"
        },
        ":focus": {
          "background-color": "#313131"
        }
      }
    }
  },
  "toggle": {
    "styles": {
      "toggle": {
        "background-color": "#363636",
        ":hover": {
          "background-color": "#313131"
        },
        ":focus": {
          "background-color": "#313131"
        }
      }
    }
  },
  "productSet": {
    "styles": {
      "products": {
        "@media (min-width: 601px)": {
          "margin-left": "-40px"
        }
      }
    }
  }
}
      });
    });
  }
})();
/*]]>*/
</script>

thanks in advance !

Fabio

**Comment by melissaluu** [comment]
@fabskills - the product `modal` template currently uses the smaller image `src` for the main image within the carousel.
https://github.com/Shopify/buy-button-js/blob/45b387afc96b909792f1863f58545a7786b83544/src/templates/product.js#L22

If you would like to use the larger image, you may set up a custom `imgWithCarousel` template where the image uses the `srcLarge` property. To see how to set up custom templates, take a look at http://shopify.github.io/buy-button-js/advanced/

**Comment by fabskills** [comment]
@melissaluu 

Thanks for your response melissa !
but i'm very noob in this sector... actually i just copy & paste the code generated within the shopify buy button dashboard after i have customised my collection. 
And in squarespace i just past the code generated in a embedded code block. My skill are limited in coding... where i need to write the custom code ? can i just tweak the code i've send below,or i need to find another ? Please Thanks for you help !

**Comment by morganmccunn** [comment]
Hey @fabskills - The docs that were shared above have additional details about what to customize if you want the large image source. However, if you need additional help on coding, Shopify Experts and the [small tasks](https://experts.shopify.com/tasks) section might be a good fit for you! You can get access to developers who can help make the coding changes to your buy button to achieve the look and feel you're going for.

Otherwise, the buy button channel is designed for folks who aren't able to modify the code themselves, and we recommend you use that generated code without making modifications to avoid having a broken button on your website. 

Good luck 🙂

**Comment by fabskills** [comment]
@morganmccunn @melissaluu Ok ! I managed to change the resolution of the images displayed but the quality is still degraded it seems that the script compresses the image quality ? can we remove that ? This is not very user friendly...

Thanks in advance !

https://intothefab.com/prints/

<div id='collection-component-694fd53f1f2'></div>
<script type="text/javascript">
/*<![CDATA[*/

(function () {
  var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';
  if (window.ShopifyBuy) {
    if (window.ShopifyBuy.UI) {
      ShopifyBuyInit();
    } else {
      loadScript();
    }
  } else {
    loadScript();
  }

  function loadScript() {
    var script = document.createElement('script');
    script.async = true;
    script.src = scriptURL;
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
    script.onload = ShopifyBuyInit;
  }

  function ShopifyBuyInit() {
    var client = ShopifyBuy.buildClient({
      domain: 'digital-nomad-adventure.myshopify.com',
      apiKey: '87aef35ebb5c90a273cd0f95f12479db',
      appId: '6',
    });

    ShopifyBuy.UI.onReady(client).then(function (ui) {
      ui.createComponent('collection', {
        id: 43837587498,
        node: document.getElementById('collection-component-694fd53f1f2'),
        moneyFormat: '%E2%82%AC%7B%7Bamount_with_comma_separator%7D%7D',
        options: {
  "product": {
    "buttonDestination": "modal",
    "variantId": "all",
    "isButton": false,
    "contents": {
      "imgWithCarousel": false,
      "variantTitle": false,
      "options": false,
      "description": false,
      "buttonWithQuantity": false,
      "quantity": false
    },
    "text": {
      "button": "VOIR PRODUIT"
    },
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "calc(50% - 40px)",
          "margin-left": "40px",
          "margin-bottom": "50px"
        }
      },
      "button": {
        "background-color": "#363636",
        ":hover": {
          "background-color": "#313131"
        },
        ":focus": {
          "background-color": "#313131"
        }
      }
    }
  },
  "cart": {
    "contents": {
      "button": true
    },
    "text": {
      "title": "Panier",
      "total": "Total",
      "notice": "\nLes codes de livraison et de réduction sont ajoutés au checkout",
      "empty": "Votre panier est vide"
    },
    "styles": {
      "button": {
        "background-color": "#363636",
        ":hover": {
          "background-color": "#313131"
        },
        ":focus": {
          "background-color": "#313131"
        }
      },
      "footer": {
        "background-color": "#ffffff"
      }
    }
  },
  "modalProduct": {
    "contents": {
      "img": false,
      "imgWithCarousel": true,
      "variantTitle": false,
      "buttonWithQuantity": true,
      "button": false,
      "quantity": false
    },
    "templates": {
      "imgWithCarousel": `<div class="{{data.classes.product.imgWrapper}}" data-element="product.imageWrapper">
                      <div class="main-image-wrapper">
                        <button type="button" class="carousel-button carousel-button--previous">
                          Left
                          <img class="carousel-button-arrow" src="//sdks.shopifycdn.com/buy-button/latest/arrow.svg" alt="Carousel Arrow"/>
                        </button>
                        <img class="{{data.classes.product.img}}" src="{{data.currentImage.srcLarge}}" data-element="product.img" />
                        <button type="button" class="carousel-button carousel-button--next">
                          Right
                          <img class="carousel-button-arrow" src="//sdks.shopifycdn.com/buy-button/latest/arrow.svg" alt="Carousel Arrow"/>
                        </button>
                      </div>
                      <div class="{{data.classes.product.carousel}}">
                        {{#data.carouselImages}}
                        <a data-element="product.carouselitem" href="{{src}}" class="{{data.classes.product.carouselItem}} {{#isSelected}} {{data.classes.product.carouselItemSelected}} {{/isSelected}}" data-image-id="{{id}}" style="background-image: url({{carouselSrc}})"></a>
                        {{/data.carouselImages}}
                      </div>
                    </div>`
    },
    "text": {
      "button": "AJOUTER AU PANIER"
    },
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "100%",
          "margin-left": "0px",
          "margin-bottom": "0px"
        }
      },
      "button": {
        "background-color": "#363636",
        ":hover": {
          "background-color": "#313131"
        },
        ":focus": {
          "background-color": "#313131"
        }
      }
    }
  },
  "toggle": {
    "styles": {
      "toggle": {
        "background-color": "#363636",
        ":hover": {
          "background-color": "#313131"
        },
        ":focus": {
          "background-color": "#313131"
        }
      }
    }
  },
  "productSet": {
    "styles": {
      "products": {
        "@media (min-width: 601px)": {
          "margin-left": "-40px"
        }
      }
    }
  }
}
      });
    });
  }
})();
/*]]>*/
</script>

**Comment by melissaluu** [comment]
@fabskills - Currently, `buy-button-js` provides the 2 image sizes mentioned above and loading the compressed images is part of the strategy to help ensure better performance when loading the buy buttons on various devices and connections.

A workaround that you can possibly utilize is to add links to the high-res images to the product description. Also, as @morganmccunn mentioned above, the Shopify Experts or small tasks site can potentially help you create more customized buy buttons.

**Comment by Atusa** [comment]
@melissaluu @michelleyschen  @morganmccunn Hi everybody. I agree with @fabskills the image resolution of srcLarge is way too low, especially for retina screens that almost everybody has now - could you consider changing this so we also have an option larger than srcLarge?

For now the limit seems like a huge disadvantage for using the buybutton - if people want to sell products, the customers need to be able to fully see them. Does not have to be ultra HD but srcLarge is still way too small..

Looking forward to hearing back from you,

**Comment by morganmccunn** [comment]
Hi @Atusa - we've opened an issue in our work board and will look into this. I will follow up when we have more information.

**Comment by jamiemtdwyer** [comment]
For carousel images, the image is loaded from the CDN according to the `options.product.width` value that is passed in when initializing the product component.

Images displayed outside of the carousel always use the hardcoded "large" size, which from the previous discussion seems to be related to performance optimization.

If you want the image outside of the carousel to be loaded in the same resolution as the provided `options.proudct.width` value, you can provide a custom template when initializing the product component.

```js
var ui = ShopifyBuy.UI.init(client);
ui.createComponent('product', {
  id: 8267093571,
  options: {
    product: {
      width: '1024px',
      templates: {
        img: '{{#data.currentImage.src}}<div class="{{data.classes.product.imgWrapper}}" data-element="product.imgWrapper"><img data-element="product.img" class="{{data.classes.product.img}}" src="{{data.currentImage.src}}" /></div>{{/data.currentImage.src}}'
      }
    }
  }
});
```

This will load the 1024px image from the CDN.

Does this solve the original issue?

**Comment by cpimhoff** [comment]
For any who stumble upon this in the future, since they merged #552 you can change the templates to reference all the originally sized images (`srcOriginal`).

This is the comment that pushed me in the right direction:
https://github.com/Shopify/buy-button-js/issues/370#issuecomment-422847099

**Comment by armaantalreja** [comment]
Hi - I am using code blocks on Squarespace and currently facing the same problem. Can someone please guide me? I can't understand how to execute this solution.

**Comment by morganmccunn** [comment]
Hi @armaantalreja the best place to get help here is in our [community forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology).

**Comment by armaantalreja** [comment]
I have posted there but never got any response. Can you please help me?

**Comment by armaantalreja** [comment]
Even others have asked for a solution and got not response. 
<img width="920" alt="Screen Shot 2020-04-15 at 10 42 33 PM" src="https://user-images.githubusercontent.com/63728281/79366846-7f773080-7f6a-11ea-9b4e-dde779439c63.png">

**Comment by armaantalreja** [comment]
I guess I am not the only one. Spent the last 1 week setting up everything on the dashboard and end up no where. This is very disheartening guys. Its been a year users  have been raising this issue. 

<img width="925" alt="Screen Shot 2020-04-15 at 11 21 54 PM" src="https://user-images.githubusercontent.com/63728281/79370408-39bd6680-7f70-11ea-8e8c-f1a029c61e60.png">
