### ISSUE TITLE
"Wrapper" Class Names not Applied

### ISSUE THREAD

**Issue by bryantwells** [Shopify/buy-button-js#377]
When options for wrapper class naming are applied to a new product component — the settings are not applied in the resulting document object. This was not working for me in the latest build (0.4.13) or the build referenced in the documentation (0.1.34). Using the following syntax:

~~~
toggle: {  
    classes: {  
        wrapper: 'wrapper-name',  
    },  
},
~~~

The following, default wrapper is still created in the document:

~~~
<div class="shopify-buy-frame shopify-buy-frame--toggle">
</div>
~~~

**Comment by rebeccajfriedman** [comment]
Closing as stale. Please reopen if problem persists.
