### ISSUE TITLE
React server side rendering `self is not defined` error

### ISSUE THREAD

**Issue by ubershmekel** [Shopify/buy-button-js#381]
When I `npm install @shopify/buy-button-js` and import it in a `https://github.com/zeit/next.js` app I get this error during the react server side rendering:

```
ReferenceError: self is not defined
```

I'm not sure of a way to conditionally include the shopify button code. This is not an issue with `shopify-buy` though I'm not sure how to get `ShopifyBuy.UI` working with that (UI seems to be undefined).

**Comment by ubershmekel** [comment]
Here's a working example with the problem. Just run `yarn` then `yarn run dev`

https://github.com/ubershmekel/shopifybuybuttonissue

**Comment by melissaluu** [comment]
We've updated all our packages recently. Reopen if this issue still occurs.
