### ISSUE TITLE
modal active class being added to wrong `html` node

### ISSUE THREAD

**Issue by harisaurus** [Shopify/buy-button-js#401]
When a modal is opened, the `.shopify-buy-modal-is-active` class is added to the `html` node like so:

```
addClassToElement('shopify-buy-modal-is-active', document.getElementsByTagName('html')[0]);
```

The class adds `height: 100%; overflow: hidden` to the `html` node which causes large blank spaces to appear and double scrolls for anyone using a them that doesn't have their `html` already styled and accomodated with those rules. (use theme "Minimal" and embed in collection description or on a page for demo purposes).

Internal ticket: https://shopify.zendesk.com/agent/tickets/6319606\

---

The temporary fix requires the addition of the following styles.
```
.shopify-buy-modal-is-active { overflow: visible; }
```

**Comment by rebeccajfriedman** [comment]
Closing as stale.
