### ISSUE TITLE
changing buttonDestination to 'onlineStore' results in 404 erros

### ISSUE THREAD

**Issue by luciphear** [Shopify/buy-button-js#403]
Problem: changing buttonDestination to 'onlineStore' so that the buy button directs the user to the full product details page results in a 404 error

Workaround: set up a redirect so that there is no 404 error

Details: The buy button passes the url in the following format:

yourShopifyDomain.myshopify.com/products/xxx?miscInfo

where xxx is the unique product ID in the shopify system

Problem is the store doesn't recognize the unique product ID

Instructions: on your redirects page, make sure /products/xxx redirects to /products/productHandle

**Comment by j-greig** [comment]
So you have to create a redirect rule for every product???

**Comment by Justinclewis94** [comment]
Has anyone found a different workaround for this?  Manually creating a new redirect every time we add a product is not an option.

**Comment by melissaluu** [comment]
A redirect should not be necessary - using the `buttonDestination: 'onlineStore'` config will redirect users to the online store product page (http://shopify.github.io/buy-button-js/customization/).
