### ISSUE TITLE
Cannot Install SSH Error

### ISSUE THREAD

**Issue by ckizer** [Shopify/buy-button-js#411]
Running NPM install on the examples. It's clear you can't get to that theme required to install. 

Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/Shopify/yuidoc-lucid-theme.git
npm ERR! 
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

**Comment by rebeccajfriedman** [comment]
Closing as stale. Please reopen if problem persists.
