### ISSUE TITLE
Buy Button - accessibility compliance checker

### ISSUE THREAD

**Issue by amyshea** [Shopify/buy-button-js#415]
I recently performed an audit on channels, and uncovered an issue with the customization of the Buy Button colour. Merchants can pick a colour that is not AA compliant 4.5:1. Suggest implementing a 'check' for this, similar to the attached example on wholesale channel. 

<img width="1182" alt="screen shot 2017-09-15 at 1 51 35 pm" src="https://user-images.githubusercontent.com/30900707/30496489-84ef0180-9a1d-11e7-8d40-2141a496e806.png">

**Comment by morganmccunn** [comment]
Closing this as it's relevant to the channel, not the .js library. Flagged it to @macaspac for future review though.
