### ISSUE TITLE
Why put `node-sass` in dependencies.

### ISSUE THREAD

**Issue by feimosi** [Shopify/buy-button-js#432]
Why is `node-sass` in dependencies instead of devDependencies?

**Comment by inklingsofreality** [comment]
I can't install via npm at all because of node-sass. Attached is the debug-log. 
[2018-05-23T12_49_36_308Z-debug.log](https://github.com/Shopify/buy-button-js/files/2031132/2018-05-23T12_49_36_308Z-debug.log)

**Comment by stenvdb** [comment]
Bumping this

It gets worse, the node-sass version required is 3.8.0 which only works up to node version 7. Please remove the node-sass dependancy. Or at least update it to a newer version.

**Comment by melissaluu** [comment]
We are tracking this in our backlog and will update this ticket when we have more information.

**Comment by colinhowells** [comment]
node-sass 3.8.0 no longer exists, as well, afaik:
```
npm i -D @shopify/buy-button-js
> node-sass@3.8.0 install [foo_path]
> node scripts/install.js
Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/darwin-x64-72_binding.node": 
HTTP error 404 Not Found
```

**Comment by colinhowells** [comment]
buy-button-js's yarn.lock had a different 'resolved' url for node-sass than npm's which 404s, so pointing my package-lock.json to yarn's url sorted things:

```
node-sass": {
	"version": "3.8.0",
	"resolved": "https://registry.npmjs.org/node-sass/-/node-sass-3.8.0.tgz",
```

**Comment by colinhowells** [comment]
This is still a thing, btw. Any chance node-sass can be updated?

**Comment by melissaluu** [comment]
Update: we're currently working on updating the packages for this project. I'll update this issue once we cut the new release.

**Comment by melissaluu** [comment]
The new [`v0.12.0` ](https://github.com/Shopify/buy-button-js/blob/master/CHANGELOG.md) is now live and has the latest `node-sass` 🎉
