### ISSUE TITLE
Is there a way to send a user ID to the checkout that can be attached to the order?

### ISSUE THREAD

**Issue by ChalkyBrush** [Shopify/buy-button-js#436]
For my website, one of the items being sold is a month of "Premium Access"
In order for this to work properly, I need to send our website's User ID with the order, which can then be sent back in the 'order created' webhook. This way my web application can properly credit the correct user account with 1 month (or however many they bought) of premium access immediately.

Is this possible?

**Comment by ChalkyBrush** [comment]
found a hacky way to do this by storing cart_id on the server and matching it to the order callback. Would still be nice to properly submit custom attributes

**Comment by tomkeysers** [comment]
Interested in this as well. 

@ChalkyBrush have you tried sending it along in the note_attributes property?

**Comment by tomkeysers** [comment]
@ChalkyBrush it can be done with the [checkoutAttributesUpdate](https://help.shopify.com/api/storefront-api/reference/mutation/checkoutattributesupdate) mutation. The `input` argument can hold custom attributes and a note.
