### ISSUE TITLE
Add note to cart

### ISSUE THREAD

**Issue by tomkeysers** [Shopify/buy-button-js#438]
Is there a possibility to send along a cart note with this library?

**Comment by tomkeysers** [comment]
Figured it out: the [checkoutAttributesUpdate](https://help.shopify.com/api/storefront-api/reference/mutation/checkoutattributesupdate) mutation query.

**Comment by Shpigford** [comment]
@tomkeysers This is a bit old...but how did you do this in the context of the BuyButton.js library? I'm trying to figure this out as well.

**Comment by tomkeysers** [comment]
@Shpigford I didn't end up using it because the client didn't need it after all, but this is the testing (jQuery) code which worked at the time:

```
var query = 'mutation checkoutAttributesUpdate($checkoutId:ID!,$input:CheckoutAttributesUpdateInput!){checkoutAttributesUpdate(checkoutId:$checkoutId,input:$input){userErrors{field message}checkout{id}}}';
	$.post({
		url: 'https://xxx.myshopify.com/api/graphql',
		data: JSON.stringify({ 
			query: query,
			variables:{"checkoutId": checkoutId, "input": {"note":"test"}}
		}),
		headers: {
			'X-Shopify-Storefront-Access-Token': 'xxx'
		},
		contentType: 'application/json'
	}).done(function(response) {
		console.log('Fetched Pokemons:', response);
	});
```
So basically I'm just calling a mutation from the Storefront API and this is not via the BuyButton.js library. The BuyButton.js library stores the checkoutID in LocalStorage so you can read that out for calling the mutations.

As I said this code did not make it live so not 100% sure if it's still working, and the [mutation also seems to have updated](https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/mutation/checkoutattributesupdatev2#interactive-example) meanwhile, but this approach should do it.

**Comment by spencercanner** [comment]
@Shpigford we've just released a new feature in buy-button-js which exposes a configuration option for cart-level notes, accessible in the cart component's contents: 
```
options: {
  ...
  "cart": {
    ....
    "contents": {
      "note": true,
      ...
    } 
  }
}
```
