### ISSUE TITLE
All lineItems show image placeholder

### ISSUE THREAD

**Issue by tomkeysers** [Shopify/buy-button-js#441]
For some reason the lineItems in my cart get the placeholder image as thumbnail, although my products do have an image which is even being loaded in the product component ... So why not in the cart component?

Developing on localhost in WordPress site.

Anyone an idea?

**Comment by marianneciara** [comment]
Apologies @tomkeysers I only just saw that you raised this as an issue here. I'll keep an eye on this thread. Have you tested it in a live environment yet?

**Comment by marianneciara** [comment]
OK so I've managed to resolve the issue by using the old version of the CDN (0.1.34):

`wp_enqueue_script( 'buy-button', 'http://sdks.shopifycdn.com/buy-button/0.1.34/buybutton.min.js', array( ), '', true );`

Using the storefront access token as the apiKey:

`var client = ShopifyBuy.buildClient({
  domain: "my-shop.myshopify.com",
  apiKey: ''your-storefront-access-token'',
  appId: '6'
});`

And wrapping all customizations in quotation marks, e.g.:

`  ui.createComponent('collection', {
    id: collectionId,
    node: node,
    options: {
      "product": {
        "buttonDestination": "modal",
        "text": {
          "button": "View Item",
        },
        "contents": {
          "options": false,
          "quantity": false,
        },
        "styles": {
          "title": {
            "font-family": "Source Sans Pro",
            "text-transform": "uppercase",
            "font-size": "14px",
            "letter-spacing": "0.6px",
          },
        }
      },
    }
  });`

This gets the product images displaying inside the cart. Does it work for you?

**Comment by tomkeysers** [comment]
Thanks for the suggestion @marianneciara ! But I would really like to keep using the up to date version because of some functionality in this library and in js-buy-sdk v1 – which is not in the old version.

So hopefully they'll fix this bug :)

**Comment by lloydstubber** [comment]
Second this! Every site I'm using the buy button on (just copied from the Shopify admin) is missing the image. Any ideas how to fix?

**Comment by tomkeysers** [comment]
Do you encounter this issue using the latest release @lloydstubber ? 
I haven't been able to test since v0.5.1 – but will do soon – and it seems it might have been solved in later releases.

**Comment by lloydstubber** [comment]
I just have this setup for clients that just copy and paste from Shopify. Seems it's using this script which is v1.5.0: `https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js`

Guessing this was a breaking change? As I wasn't having this issue yesterday

**Comment by tomkeysers** [comment]
Oh I see, your client uses the Buy Button embed and not this actual UI library.

I guess that buy-button-storefront script you reference is probably somehow in sync with or depending on this library – which would justify experiencing the same bug – but as far as I can tell it is not available in any github repo ... So I have no idea how you could downgrade that script to an earlier, bugless, version.

Good question for the Shopify guys, but unfortunately they're not really responsive in this repo.

**Comment by tomkeysers** [comment]
To follow up: I just tested v0.5.4 and the thumbnail issue still persist.

**Comment by lloydstubber** [comment]
Hmm interesting. I'll try and see if I can reach out to someone at Shopify. Cheers!

**Comment by lloydstubber** [comment]
I posted a few times in the Shopify Plus/Partners Slack with no response but this seems to have been fixed now!

**Comment by supaht** [comment]
Hi there, I'm having this issue with the line item images displaying the placeholder images for all versions from 5.0 - 6.1. If I use 4.13 it's fine. I'm using the cdn. Any updates on this?

**Comment by StefanSlehta** [comment]
`0.6.7` [is passing an image](https://github.com/Shopify/buy-button-js/blob/master/src/components/cart.js#L130) to the cart
