### ISSUE TITLE
Cart.addVariantToCart() now fails with "data is undefined"

### ISSUE THREAD

**Issue by saitho** [Shopify/buy-button-js#472]
I'm trying to add a product to the cart by calling the .addVariantToCart() method on the cart component. It used to work – the latest release seems to have broken my configuration...
Now I get the error:
```
TypeError
columnNumber: 9
fileName: "https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.js"
lineNumber: 3591
message: "data is undefined"
stack: "handleCheckoutMutation/<@https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.js:3591:9\n"
```
This is how I get the cart component. I create the component and save the response (the cart object) in a global variable:
```
ui.createComponent('cart', {
    node: document.getElementById('product-component'),
    moneyFormat: encodeURI(shopifyLocale.currencyFormat),
    options: {cart: cartConfig}
}).then((component) => {
    cartComponent = component;
}).catch((error) => {
    // this is triggered...
    console.error(error);
});
```

My "Add to cart" buttons then add the product variant using the addVariantToCart method.
```
cartComponent.addVariantToCart(productVariant).then(() => {
}).catch((error) => console.error(error));
```

_productVariant_ is the full product variant object passed by the API:
<img width="544" alt="shopify_variant" src="https://user-images.githubusercontent.com/7293310/38879235-2300ddec-4263-11e8-8084-09b154680ec6.png">

Any idea what I'm missing?

**Comment by saitho** [comment]
I dug deeper into GraphQL and noticed this error message:

> Variable lineItems of type [CheckoutLineItemInput!]! was provided invalid value
> Explanation: Could not coerce value 7459638345781 to ID

Now I think this issue rather belongs to the buy-sdk project...
Still I believe the variant ID above is correct. I get this value directly via the Shopify API.

Also I should mention that when everything worked fine I was in the free 14 days trial for Shopify Lite. Now I'm subscribed to Shopify Lite. Could this cause the problems somehow? :O

**Comment by saitho** [comment]
I found out that I have to use a base64-encoded admin_graphql_api_id as id and pass that to addVariantToCart. Not sure why it worked before, maybe there were changes to the API. I'm closing this issue as it's solved. :)

**Comment by muzuitech** [comment]
Anyone have idea how to configure styling of cart in cartconfig using ui.createComponen({}); ?
If yes please provide me that example. It is taking default green color always when I try to create using createcomponent

Thanks
