### ISSUE TITLE
Toggle Not Displaying For First Cart Item

### ISSUE THREAD

**Issue by pinpointpanda** [Shopify/buy-button-js#476]
I'm seeing a strange issue whereby the toggle is NOT displaying when only one item is added to the cart.
Adding a second item will force it to appear.

This behaviour is replicable, you can see it in the CodePen here (this was in the blog article when the BuyButton JS was launched):
https://codepen.io/tessa-lt/pen/KgByGO

Steps to recreate:

1. Add a 'Small Black Dress' to the cart.
2. Close the cart.
(the toggle is **not displayed**, but should be)
3. Now add another item.
(the toggle is displayed correctly)
4. Remove one item from the cart.
(the toggle is displayed correctly)

This behaviour mirrors exactly what I'm seeing on my development site.

Any ideas?

**Comment by pinpointpanda** [comment]
Seems this is to do with how the iFrame is resized in the resizeX() function.
The first time an item is added, the iFrame still has width:0px, the second and all subsequent times, the width is set correctly.

I've fixed temporarily with a CSS hack to force the iframe's width:
```
.shopify-buy-frame--toggle iframe {
  min-width:46px!important;
}
```

**Comment by bphippen** [comment]
I also ran into that issue and it was due to using an older version of the buy button js file.

This is the include script I am using now and the issue went away. Looks like the latest at the time of this comment is v1.11.1

`https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js`

**Comment by pinpointpanda** [comment]
Ahhh that's a big help, thank you. I'll make sure I'm using a more recent
version!
