### ISSUE TITLE
Collection doesn't load/appear in desktop browser, but does in mobile browser

### ISSUE THREAD

**Issue by JHuppi** [Shopify/buy-button-js#479]
I have a collection on two pages:
[https://www.highmountainsage.com/shop](https://www.highmountainsage.com/shop) 
[https://www.highmountainsage.com/shop/waxes](https://www.highmountainsage.com/shop/waxes)
that doesn't load or appear when viewing from a desktop browser (I've tested Chrome, Firefox, Safari), but does appear/load from the previously listed browsers' mobile versions.

When I check the console there is an error and it reads:
`
TypeError: Cannot read property 'id' of null
    at e.get (buybutton.min.js:6)
    at e.get (buybutton.min.js:6)
    at e.get (buybutton.min.js:6)
    at e.t.render (buybutton.min.js:6)
    at e.render (buybutton.min.js:6)
    at buybutton.min.js:6
`
The strange thing is the collection appears when I open the developer tools in Chrome and Firefox.

I don't believe the id of the collection is incorrect because my code works correctly in mobile browsers. Here is the code that creates the collection component:
`ui.createComponent("collection", {
    id: "14123630621",
    node: document.getElementById("waxes"),
    options: optionSettings
});`

Any insight would be greatly appreciated, thanks in advance!

**Comment by yodakohl** [comment]
I had a similar problem after deleting a product variant. Clearing the browser cache did the trick for me but this does not solve the problem for customers. Did you delete a product variant recently?

**Comment by JHuppi** [comment]
I think I found the problem, the shop owner had added a product to the collection that didn't have a photo yet. I disabled it from the API sales channel and now the collection appears in the browser.

I don't think this is the intentional behavior of the API so I'm going to leave the issue open for the next week or so.
