### ISSUE TITLE
BuyButton fails to load if the cart previously had items in it

### ISSUE THREAD

**Issue by niventc** [Shopify/buy-button-js#488]
Hello,

My partner uses the buy button on her Wordpress site. Recently we went on the site and noticed none of the buy button bits were loading.

A quick check in the console shows the error:

```
TypeError: Cannot read property 'image' of null
    at e.imageForLineItem (buy-button-storefront.min.js:8)
    at buy-button-storefront.min.js:8
    at Array.reduce (<anonymous>)
    at e.get (buy-button-storefront.min.js:8)
    at e.get (buy-button-storefront.min.js:8)
    at e.t.render (buy-button-storefront.min.js:7)
    at e.render (buy-button-storefront.min.js:8)
    at buy-button-storefront.min.js:7
```

The error occurs as the result from the graphql query doesn't return variants for the item in the cart, and subsequently blows up. An immediate fix for this could be to change line 132 in src/components/cart.js from

`if (lineItem.variant.image) {`

to

`if (lineItem.variant && lineItem.variant.image) {`

However I haven't tested it, and wouldn't be sure this fully fixes the issue, for a start the cart would probably still struggle to render the item.

After a bit more delving into how the cart is restored, I tried deleting the local storage, which on the next reload seems to fix the issue.

Not sure if this is a backend issue; base64 decoding the local storage value shows it contains some sort of id e.g. gid://shopify/Checkout/<ID>, or something else?

Obviously it's not an easy fix for users to do, so a potential fix could be to purge the local storage if the graphql query comes back with partial/invalid data?

Hopefully I've included enough detail, if you have any questions, let me know. If you think this sounds sensible I can always attempt to whip up a PR with the suggested changes.

Thanks,

Vince

**Comment by ianhoyte** [comment]
+1, seeing this too, thank you for identifying the issue, Vince.

**Comment by firescript** [comment]
Yes, I was getting the same error and I couldn't use the buy button until I cleared my local storage. It would just keep throwing the error in console. Once I cleared the local storage it worked fine. Got an idea when this can be fixed?

**Comment by StigAtShopify** [comment]
@morganmccunn:

Matt O'Boyle at Harper Collins reports this issue occurring for https://hcpstore.myshopify.com/admin/products/837580226621.  

![avonromancebuybutton](https://user-images.githubusercontent.com/1965855/46411080-7a33f700-c6e0-11e8-9534-bdb745b94746.png)

He reports that clearing local storage value and refreshing the page corrects the issue:
![avonromancebuybuttonslocal](https://user-images.githubusercontent.com/1965855/46411139-9b94e300-c6e0-11e8-998f-5fa6d116f9b0.png)

He also says:  "We’re not setting up specific variants for our products, other than the default variant that gets created with the product."
