### ISSUE TITLE
shopify buy button, I need to display all products of the collection

### ISSUE THREAD

**Issue by mhmdbdwy** [Shopify/buy-button-js#539]
I'm using shopify Buy button and i have a collection contains more than 40 products
the code is displaying 20 products only then a button to load more products
i need to display all of the 40 products
here is my code
`<div id='collection-component-e5e94b02651'></div>
    <script type="text/javascript">
    /*<![CDATA[*/

    (function () {
      var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';
      if (window.ShopifyBuy) {
        if (window.ShopifyBuy.UI) {
          ShopifyBuyInit();
        } else {
          loadScript();
        }
      } else {
        loadScript();
      }

      function loadScript() {
        var script = document.createElement('script');
        script.async = true;
        script.src = scriptURL;
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
        script.onload = ShopifyBuyInit;
      }

      function ShopifyBuyInit() {
        var client = ShopifyBuy.buildClient({
          domain: 'villabate-alba-shipping.myshopify.com',
          storefrontAccessToken: '3069fe7f19924ab2428e41e3185ccf8e',
	
        });

        ShopifyBuy.UI.onReady(client).then(function (ui) {
          ui.createComponent('collection', {
            id: 11722096688,
            node: document.getElementById('collection-component-e5e94b02651'),
            moneyFormat: '%24%7B%7Bamount%7D%7D',
            options: {
  "product": {
  
  "buttonDestination": 'cart',
    "variantId": "all",
    "contents": {
      "imgWithCarousel": false,
      "variantTitle": false,
      "description": false,
      "buttonWithQuantity": false,
      "quantity": false
    },
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "calc(25% - 20px)",
          "margin-left": "20px",
          "margin-bottom": "50px"
        },
        "imgWrapper": {
          "position": "relative",
          "height": "0",
          "padding-top": "calc(75% + 15px)"
        },
        "img": {
          "height": "calc(100% - 15px)",
          "position": "absolute",
          "left": "0",
          "right": "0",
          "top": "0"
        }
      }
    }
  },
  "cart": {
    "contents": {
      "button": true
    },
    "styles": {
      "footer": {
        "background-color": "#ffffff"
      }
    }
  },
  "modalProduct": {
    "contents": {
      "img": false,
      "imgWithCarousel": true,
      "variantTitle": false,
      "buttonWithQuantity": true,
      "button": false,
      "quantity": false
    },
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "100%",
          "margin-left": "0px",
          "margin-bottom": "0px"
        }
      }
    }
  },
  "productSet": {
  "contents": {
  "pagination": false,
    },
    "styles": {
      "products": {
        "@media (min-width: 601px)": {
          "margin-left": "-20px"
        }
      }
    }
  }
}
          });
        });
      }
    })();
    /*]]>*/
    </script>`

please help me as soon as possible

**Comment by rebeccajfriedman** [comment]
At this time, we only support returning 20 products at once. If you are comfortable working with the [JS Buy SDK](https://github.com/Shopify/js-buy-sdk) directly, you can make many calls to fetch 20 products in rapid succession.
