### ISSUE TITLE
buy button implementation - variant selection/inventory qty display

### ISSUE THREAD

**Issue by judyschmitz** [Shopify/buy-button-js#560]
We are attempting to create a button that does two things; 1 - only displays 1 of the variants in a product, and 2 ) displays the available quantity for that variant - currently the only thing our buy button does is show ALL the variants available (unable to isolate color variants) and also only shows 'out of stock' .  Is it possible to edit the code to display information on a select variant? ANd the qty in inventory for that variant?

**Comment by melissaluu** [comment]
Hi @judyschmitz - to show a single product variant in a buy button, update the `variantId` property in the `product` options configuration object  from `all` to a specific variant id. 

```
ui.createComponent('product', {
  id: [<product-id>],
  ...
  options: {
    product: {
      ...
      variantId: <variant-id>
      ...
    }
  }
}
```
You can also use the buy button channel to generate the code snippet for a single variant button as well.

However, the buy button currently cannot show the available quantity for a product.
