### ISSUE TITLE
TypeError: undefined is not an object in Safari (MacOS and iOS)

### ISSUE THREAD

**Issue by brooms** [Shopify/buy-button-js#566]
The Cart overlay is failing to display sometimes in Safari on MacOS and iOS. It is very non-deterministic and I've not been able to get to the root cause of the error.

**Browser:** Safari Version 12.0.1 (14606.2.104.1.1)
**OS:** MacOS Mojave version 10.14.1
**Buy Button Version**: buy-button-storefront @1.12.6 

Buy button SDK is being loaded via the CDN: https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js

Full error message:

```
> [Error] TypeError: undefined is not an object (evaluating 't.message.indexOf')
(anonymous function) — buy-button-storefront.min.js:4478
promiseReactionJob

      > (anonymous function) (buy-button-storefront.min.js:8:17752)
	promiseReactionJob
```

Issue replication:

1. Go to [3dh.com.au/wine-shop](http://3dh.com.au/wine-shop)
2. Add some products to the cart and close it.
3. Browse and follow some links. (Cart overlay will eventually be unable to open)

**Update:**

Through further investigation it actually looks like it may be unrelated to the error message and in fact, the `preloader` child div under `shopify-buy-cart-wrapper` div is masking the cart overlay. The cart overlay is rendered, but it is hidden behind the preloader.

```html
<div class="shopify-buy-cart-wrapper shopify-buy-frame shopify-buy-frame--cart is-active is-initialized">
    <div class="preloader"></div>
    <iframe horizontalscrolling="no" verticalscrolling="no" allowtransparency="true" frameborder="0" scrolling="no"
            name="frame-cart" style="width: 100%; overflow: hidden; border: none;">...</iframe>
</div>
```

**Comment by spencercanner** [comment]
Hey @brooms, 
Looking into the site's graphql network calls, there seems to be a request made using an invalid product id.  We noticed that there's a div with the class `shopify-product`, which has an invalid id and thus might be causing the issue. 
`<div class="shopify-product shopify-buy-frame shopify-buy-frame--product shopify-buy__layout-vertical" style="display: none; max-width: 240px;" id="' . $id .'" shopifyid="'. $a['id']. '">`

Could you try removing this element from your site, and seeing if the issue persists?

**Comment by brooms** [comment]
Oh my. That was my fault, some bad php code was generating a dodgy `<div>`. It's a bit of a hack but to get the cart to display on every page I have included a dummy product in the footer of the site inside a hidden `<div>`. Thanks for pointing that out.

The issue of the cart being hidden by the preloader `<div>`is actually a theme issue. I have resolved it.  I'll close this issue.
