### ISSUE TITLE
insert toggle in the dom 

### ISSUE THREAD

**Issue by supaht** [Shopify/buy-button-js#569]
Hi there, 

I currently have the toggle component (the cart icon) set to sticky and pinned to the top right the screen, as part of a navigation bar. Unfortunately, when I insert an alert at the top of the page, the nav gets pushed down, but the toggle cart stays. 

Would it be possible to insert the toggle component in a specified place in the DOM, like at the end of my `<nav>`?  

Any tips would be greatly appreciated.

**Comment by robskrob** [comment]
@supaht good question. I am also curious about this. My approach has been the following:

```html
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		
         <script src="https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js"> </script>
    <script>
      var client = ShopifyBuy.buildClient({
        domain: 'myshop',
        storefrontAccessToken: 'myToken',
      });

      window.shopifyBuyClient = client;

    </script>
	</head>
  <body>
    <div id='shopify-cart' ></div>
    <div class=.minicart-wrapper' > <span class="counter-number"></span></div>
    .....
  <script>
      ShopifyBuy.UI.onReady(client).then(function (ui) {
        ui.createComponent('cart', {
          node: document.getElementById('shopify-cart'),
        });

      $(".minicart-wrapper").click(function(event){


        ShopifyBuy.UI.onReady(window.shopifyBuyClient).then(function (ui) {
          ui.openCart();
        });
  <script>
  </body>
```

This lets me open the cart when I want to; however, I cannot get the count to draw on `span.counter-number`. When I go to draw the number of items in my cart the iFrame that contains the toggle 
 is not loaded so the JavaScript I write `$('span.counter-number').text($('.shopify-buy__cart-toggle__count').textContent);` does not get the amount it's asking for. 

It would be nice if I could just write something like:
```js
ShopifyBuy.UI.onReady(client).then(function (ui) {
        ui.createComponent('cart', {
          node: document.getElementById('shopify-cart'),
        });

        ui.createComponent('toggle', {
          node: document.getElementById('minicart'),
          options: {
            "toggle": {
              "contents": {
                count: true,
                icon: true,
                title: true,
              }
            }
          }
        });
```

Where `minicart` is the element where I'd like the `component toggle` to exist. @spencercanner do you have any thoughts on inserting a toggle where one wants?

**Comment by spencercanner** [comment]
@supaht @robskrob 

You can leverage the `toggles` configuration available in buy button. This option will take a list of nodes into which you would like to insert the cart toggle. By default, this will render the default toggle into the node, however you can update its styling and contents via templates or overriding the styles. 
One thing to note is that you'll have to set the toggle's `sticky` option to false (shown below), otherwise the toggle will always appear in the middle-right of the screen. If you want it to pick up page level styles, you might also want to set the toggle's `iframe` option to false.

```
<div id='toggle' class='toggle'></div>
<div id='product-component-cb1fc855ed0'></div>
``` 

```
ShopifyBuy.UI.onReady(client).then(function (ui) {
  ui.createComponent('product', {
    ...
    node: document.getElementById('product-component-cb1fc855ed0'),
    toggles: [{node: document.getElementById('toggle')}],
    options: {
      ...
      "toggle": {
        "sticky": false,
        ...
       }
       ...
     }
  });
});
```

**Comment by robskrob** [comment]
@spencerbuttshopify thank you for sharing this code sample with me. For now, this is working. I will update this issue otherwise.

**Comment by cinghaman** [comment]
@robskrob can you please share your code how you managed to get the toggle (globally on your header nav) trying to do the same but having to add the whole js on every page.

**Comment by robskrob** [comment]
@cinghaman it has been a _long_ time since I have looked into this. 

Based on [these docs](http://shopify.github.io/buy-button-js/) looks like I am loading the script globally in my head so technically the Buy Button API is everywhere on my page. In the `head` of my document I execute the following:
```js
window.shopifyBuyClient = ShopifyBuy.buildClient({
        domain: "<?php echo env('SHOPIFY_DOMAIN'); ?>",
        storefrontAccessToken: "<?php echo env('SHOPIFY_STORE_FRONT_ACCESS_TOKEN'); ?>",
      });

window.shopifyUISingleton = ShopifyBuy.UI.init(window.shopifyBuyClient);
```

And I assign a key to the window which has the Shopify API constructed as seen above.

From this point looks like I add a JS script in a part of the HTML of my main navigation, and I believe this is how I add the shopping cart icon globally, whose implementation looks like the following:
```html
<div id='shopify-cart'></div>
      <script type="text/javascript">

        window.shopifyCart = window.shopifyUISingleton.createComponent('cart', {
          node: document.getElementById('shopify-cart'),
          toggles: [{node: document.getElementById('minicart-id')}],
          options: {
            "cart": {
              "contents": {
                "button": true
              },
              "styles": {
                "button": {
                  "background-color": "#3d1a11",
                  ":hover": {
                    "background-color": "#682c1d"
                  },
                  ":focus": {
                    "background-color": "#682c1d"
                  }
                },
              },
              "popup": false,
              events:{
                afterRender:function(component) {
                  var $iFrameContents = $(component.node).find('iframe').contents();
                  function setCorrectColorLabel($iFrameContents) {
                    let $cartSwatchLabels = $iFrameContents.find('.shopify-buy__cart-item__variant-title');

                    let colorTranslates = {
                      "Generic Black":"Black",
                      "Canvas Khaki (M)":"Canvas Khaki",
                      "Canvas Navy (M)":"Canvas Navy",
                      "Canvas Olive (M)":"Canvas Olive",
                      "Chocolate (M)":"Chocolate",
                      "Rust (M)":"Rust",
                      "Rust (W)":"Rust"
                    }

                    $cartSwatchLabels.each(function(index, cartSwatchLabel){
                      var cartSwatchLabelText = $(cartSwatchLabel).text();
                      if (colorTranslates[cartSwatchLabelText]) {
                        $(cartSwatchLabel).text(colorTranslates[cartSwatchLabelText]);
                      }
                    });
                  }

                  setCorrectColorLabel($iFrameContents);
                }
              }
            },
            "toggle": {
              events: {
                "beforeRender": function (component) {
                  var $iFrameContents = $(component.node).find('iframe').contents();
                  
                  var $head = $($iFrameContents).find('head');

                  if ($head.find('style').length === 1) {
                    $head.append($("#legacy-font-1").clone());
                    $head.append($("#legacy-font-2").clone());
                    $head.append($("#font-awesome").clone());
                  }
                },
              },
              "templates":{
                icon: '<i class="fa fa-shopping-bag"></i>',
                count: '<div class="{{data.classes.toggle.count}}" data-element="toggle.count">Bag ({{data.count}})</div>',
              },
              "sticky": false,
              "classes":{
                "fa":"fa"
              },
              "styles": {
                "toggle": {
                  "background-color": "#3d1a11",
                  "display":"inline-flex",
                  "align-items":"center",
                  "flex-direction":"row-reverse",
                  "background-color":"#fff",
                  "padding":"0px !important",
                  ":hover": {
                    "background-color": "#fff"
                  },
                  ":focus": {
                    "background-color": "#fff"
                  },
                  "color":"#3d3b3a"
                },
                "count":{
                  "margin-bottom":"0px",
                  "margin-left":"10px",
                  "font-size":"12px",
                  "font-family":"proxima-nova",
                  "text-transform":"uppercase",
                  "@media (max-width:50px)":{
                    "display":"none !important"
                  }
                },
                "fa":{
                  "@media (max-width:50px)":{
                    "font-size":"20px !important",
                  }
                }
              }
            },
          }
        });
      </script>
    </div>
```

As I read what I did I personally cringe, but I was working on a hacky wordpress project at the time. I am happy to say that I don't work on those types of projects anymore. 

You were asking about adding the shopping cart toggle, right? I'm sorry if this doesn't answer your question.

**Comment by cinghaman** [comment]
> @cinghaman it has been a _long_ time since I have looked into this.
> 
> Based on [these docs](http://shopify.github.io/buy-button-js/) looks like I am loading the script globally in my head so technically the Buy Button API is everywhere on my page. In the `head` of my document I execute the following:
> 
> ```js
> window.shopifyBuyClient = ShopifyBuy.buildClient({
>         domain: "<?php echo env('SHOPIFY_DOMAIN'); ?>",
>         storefrontAccessToken: "<?php echo env('SHOPIFY_STORE_FRONT_ACCESS_TOKEN'); ?>",
>       });
> 
> window.shopifyUISingleton = ShopifyBuy.UI.init(window.shopifyBuyClient);
> ```
> 
> And I assign a key to the window which has the Shopify API constructed as seen above.
> 
> From this point looks like I add a JS script in a part of the HTML of my main navigation, and I believe this is how I add the shopping cart icon globally, whose implementation looks like the following:
> 
> ```
> <div id='shopify-cart'></div>
>       <script type="text/javascript">
> 
>         window.shopifyCart = window.shopifyUISingleton.createComponent('cart', {
>           node: document.getElementById('shopify-cart'),
>           toggles: [{node: document.getElementById('minicart-id')}],
>           options: {
>             "cart": {
>               "contents": {
>                 "button": true
>               },
>               "styles": {
>                 "button": {
>                   "background-color": "#3d1a11",
>                   ":hover": {
>                     "background-color": "#682c1d"
>                   },
>                   ":focus": {
>                     "background-color": "#682c1d"
>                   }
>                 },
>               },
>               "popup": false,
>               events:{
>                 afterRender:function(component) {
>                   var $iFrameContents = $(component.node).find('iframe').contents();
>                   function setCorrectColorLabel($iFrameContents) {
>                     let $cartSwatchLabels = $iFrameContents.find('.shopify-buy__cart-item__variant-title');
> 
>                     let colorTranslates = {
>                       "Generic Black":"Black",
>                       "Canvas Khaki (M)":"Canvas Khaki",
>                       "Canvas Navy (M)":"Canvas Navy",
>                       "Canvas Olive (M)":"Canvas Olive",
>                       "Chocolate (M)":"Chocolate",
>                       "Rust (M)":"Rust",
>                       "Rust (W)":"Rust"
>                     }
> 
>                     $cartSwatchLabels.each(function(index, cartSwatchLabel){
>                       var cartSwatchLabelText = $(cartSwatchLabel).text();
>                       if (colorTranslates[cartSwatchLabelText]) {
>                         $(cartSwatchLabel).text(colorTranslates[cartSwatchLabelText]);
>                       }
>                     });
>                   }
> 
>                   setCorrectColorLabel($iFrameContents);
>                 }
>               }
>             },
>             "toggle": {
>               events: {
>                 "beforeRender": function (component) {
>                   var $iFrameContents = $(component.node).find('iframe').contents();
>                   
>                   var $head = $($iFrameContents).find('head');
> 
>                   if ($head.find('style').length === 1) {
>                     $head.append($("#legacy-font-1").clone());
>                     $head.append($("#legacy-font-2").clone());
>                     $head.append($("#font-awesome").clone());
>                   }
>                 },
>               },
>               "templates":{
>                 icon: '<i class="fa fa-shopping-bag"></i>',
>                 count: '<div class="{{data.classes.toggle.count}}" data-element="toggle.count">Bag ({{data.count}})</div>',
>               },
>               "sticky": false,
>               "classes":{
>                 "fa":"fa"
>               },
>               "styles": {
>                 "toggle": {
>                   "background-color": "#3d1a11",
>                   "display":"inline-flex",
>                   "align-items":"center",
>                   "flex-direction":"row-reverse",
>                   "background-color":"#fff",
>                   "padding":"0px !important",
>                   ":hover": {
>                     "background-color": "#fff"
>                   },
>                   ":focus": {
>                     "background-color": "#fff"
>                   },
>                   "color":"#3d3b3a"
>                 },
>                 "count":{
>                   "margin-bottom":"0px",
>                   "margin-left":"10px",
>                   "font-size":"12px",
>                   "font-family":"proxima-nova",
>                   "text-transform":"uppercase",
>                   "@media (max-width:50px)":{
>                     "display":"none !important"
>                   }
>                 },
>                 "fa":{
>                   "@media (max-width:50px)":{
>                     "font-size":"20px !important",
>                   }
>                 }
>               }
>             },
>           }
>         });
>       </script>
>     </div>
> ```
> 
> As I read what I did I personally cringe, but I was working on a hacky wordpress project at the time. I am happy to say that I don't work on those types of projects anymore.
> 
> You were asking about adding the shopping cart toggle, right? I'm sorry if this doesn't answer your question.

Hi yes i am adding toggle to header navigation and then have a couple of products (its a webflow project), so i am just wondering on the page where you have the products that means this script is being added twice? or you conditionally removed the header script when the page with products was being loaded?

**Comment by robskrob** [comment]
Ok yeah so this is why I think I do the following in the `head`:
```
window.shopifyUISingleton = ShopifyBuy.UI.init(window.shopifyBuyClient);
```
From this point onwards -- either on the product detail page (PDP) or on the top main nav for the cart toggle -- in my JS I reference `window.shopifyUISingleton`, which means I only construct the buy button API once, and I use this same constructed instance for the PDP as well as for the global cart toggle. 

However, I do indeed always have the script, `<script src="http://sdks.shopifycdn.com/buy-button/1.0.0/buybutton.js"></script>`, in the `head` of my HTML document.

**Comment by cinghaman** [comment]
> Ok yeah so this is why I think I do the following in the `head`:
> 
> ```
> window.shopifyUISingleton = ShopifyBuy.UI.init(window.shopifyBuyClient);
> ```
> 
> From this point onwards -- either on the product detail page (PDP) or on the top main nav for the cart toggle -- in my JS I reference `window.shopifyUISingleton`, which means I only construct the buy button API once, and I use this same constructed instance for the PDP as well as for the global cart toggle.
> 
> However, I do indeed always have the script, `<script src="http://sdks.shopifycdn.com/buy-button/1.0.0/buybutton.js"></script>`, in the `head` of my HTML document.

Thanks got it hopefully I can get it to work, but i think shopify should come up with a better documentation and update the js as well.

**Comment by cinghaman** [comment]
> Ok yeah so this is why I think I do the following in the `head`:
> 
> ```
> window.shopifyUISingleton = ShopifyBuy.UI.init(window.shopifyBuyClient);
> ```
> 
> From this point onwards -- either on the product detail page (PDP) or on the top main nav for the cart toggle -- in my JS I reference `window.shopifyUISingleton`, which means I only construct the buy button API once, and I use this same constructed instance for the PDP as well as for the global cart toggle.
> 
> However, I do indeed always have the script, `<script src="http://sdks.shopifycdn.com/buy-button/1.0.0/buybutton.js"></script>`, in the `head` of my HTML document.

This shopifyUISingleton isn't official? as I couldn't find any details about it

**Comment by robskrob** [comment]
@cinghaman sounds good -- so yeah `shopifyUISingleton` is a convention I made. As I was demonstrating before I construct the "singleton" on the window in the `head` of my document:
```
window.shopifyUISingleton = ShopifyBuy.UI.init(window.shopifyBuyClient);
```
From this point forward for the toggle I reference the "singleton". This is in my main navigation for the cart toggle:
```javascript
window.shopifyUISingleton.createComponent('cart', {...})
```

and this is on my PDP:
```javascript
window.shopifyUISingleton.createComponent('product', {...});
```
In each part of my frontend I reference the same running instance of `ShopifyBuy.UI.init(window.shopifyBuyClient);` on the `window` so I do not have to re-init the shopify buy button again.

Yes I also agree with you the documentation could be improved in these regards.

**Comment by cinghaman** [comment]
> > Ok yeah so this is why I think I do the following in the `head`:
> > ```
> > window.shopifyUISingleton = ShopifyBuy.UI.init(window.shopifyBuyClient);
> > ```
> > 
> > 
> > From this point onwards -- either on the product detail page (PDP) or on the top main nav for the cart toggle -- in my JS I reference `window.shopifyUISingleton`, which means I only construct the buy button API once, and I use this same constructed instance for the PDP as well as for the global cart toggle.
> > However, I do indeed always have the script, `<script src="http://sdks.shopifycdn.com/buy-button/1.0.0/buybutton.js"></script>`, in the `head` of my HTML document.
> 
> Thanks got it hopefully I can get it to work, but i think shopify should come up with a better documentation and update the js as well.

Thanks :) got it

**Comment by cinghaman** [comment]
> @cinghaman sounds good -- so yeah `shopifyUISingleton` is a convention I made. As I was demonstrating before I construct the "singleton" on the window in the `head` of my document:
> 
> ```
> window.shopifyUISingleton = ShopifyBuy.UI.init(window.shopifyBuyClient);
> ```
> 
> From this point forward for the toggle I reference the "singleton". This is in my main navigation for the cart toggle:
> 
> ```js
> window.shopifyUISingleton.createComponent('cart', {...})
> ```
> 
> and this is on my PDP:
> 
> ```js
> window.shopifyUISingleton.createComponent('product', {...});
> ```
> 
> In each part of my frontend I reference the same running instance of `ShopifyBuy.UI.init(window.shopifyBuyClient);` on the `window` so I do not have to re-init the shopify buy button again.
> 
> Yes I also agree with you the documentation could be improved in these regards.

Thanks got it :)
