### ISSUE TITLE
IE11 - unable to get property "valueOf" of undefined or null reference

### ISSUE THREAD

**Issue by mikeriley131** [Shopify/buy-button-js#575]
I'm using the Buy Button script herew - https://cpbgroup.com/shop/human-lie-detector-shirt - however only in IE11 I am getting the following error:

`unable to get property "valueOf" of undefined or null reference`

And the iframe does not load at all.

The site is built on Gatsby if that makes any difference.

**Comment by spencercanner** [comment]
Hey @mikeriley131, we took a quick look at your site, and we've isolated the problem to the inclusion of a [polyfill script](https://cdn.polyfill.io/v2/polyfill.js?features=default,Symbol) on your webpage.

**Comment by mikeriley131** [comment]
@spencercanner Thanks. I'll dig in and see if I can find a solution.
