### ISSUE TITLE
Redirect after checkout

### ISSUE THREAD

**Issue by hardfire** [Shopify/buy-button-js#596]
I have been playing around with the cart and checkout-popup flow of the buy button and cannot find a way to redirect the parent page to a specific URL if a checkout has succeeded. 
What would be the best way to acheive such a flow so that we can do some post-purchase thanking on our own page.

**Comment by hardfire** [comment]
@rebeccajfriedman thank you for your suggestion. I was trying to check where i could find the checkout object and realized that the page redirects after a successful order. It probably is because of this - https://github.com/Shopify/buy-button-js/blob/master/src/ui.js#L324.
Will the checkout object be still valid after the redirect? Also, how do i access it? 
Thankyou for being patient with my queries :D

**Comment by gobigthirst** [comment]
@hardfire were you able to figure this out?
