### ISSUE TITLE
How to disable out of stock variant option?

### ISSUE THREAD

**Issue by jmathew1991** [Shopify/buy-button-js#602]
I'm trying to reproduce the behavior in this [codepen](https://codepen.io/tessa-lt/pen/KgByGO) which uses v0.1.34. I want to disable options that don't have variants in stock.

When using v0.9.1 that behavior is no longer there. Is there anyway to have that behavior with the latest version of BuyButton.js

**Comment by rebeccajfriedman** [comment]
You can use the `availableForSale` boolean field on a product or variant to see if it is in stock / out of stock.

**Comment by robskrob** [comment]
@rebeccajfriedman I searched through the documentation and do not see any examples that use `availableForSale`. I also searched through the entire repo and could not see where `availableForSale` -- in other words in the absence of documentation I was trying to see how `availableForSale` could work and I just couldn't find this API `availableForSale`.

Do you have any examples of how `availableForSale` can be used?
