### ISSUE TITLE
iframe:false does not work with collections

### ISSUE THREAD

**Issue by TheRealFreelancer** [Shopify/buy-button-js#611]
**"iframe: false"** does not seem to work with **products in collections** and **product modals in collections**. The iframe is still there. _Only the **cart** can be freed from the iframe._

**Comment by melissaluu** [comment]
@TheRealFreelancer - in order to turn off iframes for collections, you'll need to set the `iframe` property within the `productSet` and `modal` config objects to `false`.

The option object:
```
{
   ...
   productSet: {
      iframe: false
   },
   modal: {
      iframe: false
   }
    ...
}
```

**Comment by TheRealFreelancer** [comment]
@melissaluu that actually worked... 👍 

Thanks for the clarification. The manual wasn't as clear.

Cheers

**Comment by lamellama** [comment]
> @melissaluu that actually worked... 👍
> 
> Thanks for the clarification. The manual wasn't as clear.
> 
> Cheers

I agree, the documentation lacks detail
