### ISSUE TITLE
CART CHECKOUT does not work on other sites – "cart empty" after Login

### ISSUE THREAD

**Issue by TheRealFreelancer** [Shopify/buy-button-js#612]
My Shopify store is configured to recommend customers have accounts in order to purchase items.

When I use the **Buy Button on another website**, not associated to Shopify (it's "Xenforo" forum software) and the Buy Buttons can add products to a "cart" on the external website, the "checkout" process from the cart redirects to the Shopify store and asks for a login. _After the customer has logged in the Shopping Cart is **"empty"**._ The products are available on both the Shopify Store and with the Buy Button channels. It seems that the token or code to update the cart/checkout is not kept after/through login to the customer account...

**Comment by morganmccunn** [comment]
This was addressed in a separate conversation with @TheRealFreelancer and appears to be an issue with the custom implementation.

Closing this out as we have no other reports of this issue at this time.
