### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by supaht** [Shopify/buy-button-js#615]
Hi there, is there a published changelog for releases? I couldn't find one in the repo and don't see anything noted in the releases section.

**Comment by morganmccunn** [comment]
Hey @supaht  - we post any significant feature changes in the developer changelog: https://developers.shopify.com/changelog

We do version bumps for minor changes roughly every 4-6 weeks. In the past four months, we've done an update about every month. This is mostly maintenance stuff and not feature based. We'll look to implement something more detailed in the coming weeks 🙂

**Comment by rebeccajfriedman** [comment]
We also implemented a changelog: https://github.com/Shopify/buy-button-js/blob/master/CHANGELOG.md

**Comment by supaht** [comment]
Excellent!!
