### ISSUE TITLE
TypeError: Cannot read property 'images' of null

### ISSUE THREAD

**Issue by luciddesignconcepts** [Shopify/buy-button-js#621]
For some reason the buybutton.js errors out only on certain products. The specific product does have images for the main and all variants.

~~~~
ui.createComponent('product', {
    id   : 123456,
    node : document.getElementById('redeem-btn'),
    options : {
        cart : {
            iframe: false
        },
        toggle  : {
            styles   : {
                toggle : {
                    'border'           : 'none',
                    'background-color' : '#0f0f0f',
                    ':hover' : {
                        'background-color' : '#f40'
                    }
                }
            },
            contents : {
                icon  : true,
                count : true,
                title : false,
            }
        },
        product : {
            text     : { button: 'Redeem' },
            iframe   : false,
            contents : {
                img   : false,
                title : false,
                price : false
            },
            templates : {
                button : '<button class="btn btn-primary {{data.classes.product.button}}">{{data.buttonText}}</button>'
            },
            buttonDestination : 'checkout'
        },
    }
});
~~~~

**Comment by rebeccajfriedman** [comment]
Hey @luciddesignconcepts - can you verify that the product is published to the channel that you are trying to access it from?

**Comment by luciddesignconcepts** [comment]
Hey @rebeccajfriedman,
It is published. Interestingly enough, we got it working by adding multiple images to the product. For some odd reason, it errors out only when there is only 1 image uploaded to the product.

**Comment by rebeccajfriedman** [comment]
Great to hear! I'm going to close this issue out. Feel free to reopen it if you experience this type of behaviour again.

**Comment by luciddesignconcepts** [comment]
@rebeccajfriedman,
The fix for us was kind of a hack. You might still want to fix it from throwing an error out if there is only 1 product image.

**Comment by rebeccajfriedman** [comment]
I can't replicate this issue. If you're open to it, can you email custom-storefronts@shopify.com with your shop name and the affected products and we can look into what went wrong?

**Comment by stolinski** [comment]
I’m getting this same issue with basic usage from NPM.  Seems weird to close this out when it wasn’t resolved.

My code looks like, client initializing omitted.

```
    const ui = ShopifyBuy.UI.init(client)
    ui.createComponent("product", {
      id: product.id,
      node: document.getElementById("button"),
    })
```

My product is published.

**Comment by stolinski** [comment]
FYI for future people finding this, my issue is that Shopify’s API apparently gives you strings that need to be Base64 encoded. Why don’t the docs mention that anywhere?

**Comment by iamkevingreen** [comment]
I'm also getting this, I'm not even using the images from the buy-sd, I'm only using it to fetch if the product is available. 

```
function fetchResourcesForProducts(productOrProduct, client) {
  var products = [].concat(productOrProduct);

  return Promise.all(products.reduce(function (promiseAcc, product) {
    // Fetch the rest of the images and variants for this product
    promiseAcc.push(client.fetchAllPages(product.images, { pageSize: 250 }).then(function (images) {
      product.attrs.images = images;
    }));

    promiseAcc.push(client.fetchAllPages(product.variants, { pageSize: 250 }).then(function (variants) {
      product.attrs.variants = variants;
    }));

    return promiseAcc;
  }, []));
}
```
