### ISSUE TITLE
Description stripped of html.

### ISSUE THREAD

**Issue by Geestig** [Shopify/buy-button-js#622]
After looking around I can't find a solution to my issue. In my shopify back-end I add some markup to my description text. (e.g. linebreaks, bold text) however when I want to show this on my front-end it only shows 1 long string.

   ```
   product: {
        iframe: false,
        order: ['img', 'title', 'price', 'description', 'options', 'button'],
        contents: {
          description: true,
        },
        text: {
          button: 'Koop nu',
          outOfStock: 'Niet langer in voorraad',
          unavailable: 'Onbeschikbaar',
        },
        templates: {
          description: '<div class="text-center text-green-darker my-5 px-12 leading-normal text-sm {{data.classes.product.description}}">{{data.description}}</div>'
        }
      },
```

I'm probably missing some option here.

**Comment by melissaluu** [comment]
Hi @Geestig - the data property you should be using is `data.descriptionHtml` with triple curly braces.

Take a look at the existing product template for an example - https://github.com/Shopify/buy-button-js/blob/b6c4eb612c786a4a16733d5c39e774088ea0e00f/src/templates/product.js#L43.

**Comment by Geestig** [comment]
Thanks for the reply, must have overlooked that one!

**Comment by Geestig** [comment]
Thanks for the solution! Must have overlooked it somehow.
