### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response

### ISSUE THREAD

**Issue by mahlingam** [Shopify/buy-button-js#624]
We are in development and since a few days, testers see in browser console:

> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://SHOP_NAME.myshopify.com/api/graphql with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

- Buy Button does not appear. 
- Shift+Reload fixes this. 

This is a blocker for our Shopify Plus enterprise integration.

**Comment by mahlingam** [comment]
This seems to be the underlying cause: https://github.com/Shopify/js-buy-sdk/issues/657

**Comment by rebeccajfriedman** [comment]
Hi @mahlingam - Did you manage to fix this? Can you let us know your shop domain (there is not enough information provided here to help us understand what's going on)?

**Comment by picooose** [comment]
Getting the same warning here @rebeccajfriedman. Using Chrome 74 and the v2.2.4 release.

It seems this issue here isn't solved: [Shopify/js-buy-sdk#657](https://github.com/Shopify/js-buy-sdk/issues/657)

> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://mydomain.com/api/graphql with MIME type text/html

Any idea how to solve this issue?

**Comment by morganmccunn** [comment]
Hey folks, any other details or steps you can provide us to help us reproduce this? Thanks

**Comment by picooose** [comment]
Hey @morganmccunn, thanks for checking in. Problem seems to be fixed for me in Chrome 75.

**Comment by SripatiDas** [comment]
> Hey folks, any other details or steps you can provide us to help us reproduce this? Thanks

I have my private app store URL: https://yolcans.myshopify.com/admin/api/2019-04/customers.json and trying to access it using spring boot angular JS app. Its throwing CORS error:

Access to XMLHttpRequest at 'https://yolcans.myshopify.com/admin/api/2019-04/customers.json' from origin 'http://localhost:7171' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

In postman, APIs are working fine. Trying to do CRUD in my angular JS app by my private store.

Is there any help as I got blocked here? Thanks...

**Comment by meuschke** [comment]
I am still getting this issue from time to time (Version 75.0.3770.100 (Official Build) (64-bit)). We are using nuxt apollo to call the GraphQl endpoint. So it seems that it is an issue with the API instead of js-buy-sdk directly.

**Comment by mahlingam** [comment]
The browser console message was not responsible for our buy button to disappear, it seems it is just a warning, not an error. We had some problems correctly resolving sequences of futures in our server side akka code, that's why the 'id' and 'variantId' values have been missing _sometimes_, when calling ui.createComponent('product',...)
