### ISSUE TITLE
Returned errors for ProductSet options

### ISSUE THREAD

**Issue by KimKJDesigns** [Shopify/buy-button-js#626]
Adding a class to the following option throws `TypeError: Cannot read property 'className' of null`

```
productSet: {
  iframe: false,
  classes: {
    products: 'shopify-buy__collection-products',
  }
},
```

And setting `pagination: false` on the contents of the option throws `Uncaught (in promise) TypeError: Cannot read property 'nodeType' of null`. Also mentioned #454

```
productSet: {
  iframe: false,
  contents: {
    pagination: false,
  },
}
```

**Comment by melissaluu** [comment]
Hi @KimKJDesigns - we're unable to reproduce the `className` error and we've add #454 to our backlogs and will mark this one as a duplicate.
