### ISSUE TITLE
Request has been blocked by CORS policy

### ISSUE THREAD

**Issue by SripatiDas** [Shopify/buy-button-js#628]
I have my private app store URL: https://yolcans.myshopify.com/admin/api/2019-04/customers.json and trying to access it using spring boot angular JS app. Its throwing CORS error:

`angular.min.js:109 OPTIONS https://yolcans.myshopify.com/admin/api/2019-04/customers.json 401 (Unauthorized)
(anonymous) @ angular.min.js:109
q @ angular.min.js:104
(anonymous) @ angular.min.js:102
(anonymous) @ angular.min.js:136
$digest @ angular.min.js:147
$apply @ angular.min.js:151
(anonymous) @ angular.min.js:22
invoke @ angular.min.js:44
c @ angular.min.js:22
Uc @ angular.min.js:22
we @ angular.min.js:21
(anonymous) @ angular.min.js:334
b @ angular.min.js:38
userLandingPage:1 Access to XMLHttpRequest at 'https://yolcans.myshopify.com/admin/api/2019-04/customers.json' from origin 'http://localhost:7171' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

In postman, APIs are working fine. Trying to do CRUD in my angular JS app by my private store & chrome browser (I would prefer not to fix in browser wise handlings).

Is there any quick help as I got blocked here? Thanks...

**Comment by rebeccajfriedman** [comment]
This repo is for those using the BuyButton.js library. Perhaps a better spot for your question would be the [Shopify Forums](https://community.shopify.com/c/Shopify-Community/ct-p/en).
