### ISSUE TITLE
Modal options not isolated between products

### ISSUE THREAD

**Issue by nickembrey** [Shopify/buy-button-js#682]
If I have two Buy Buttons representing two products on my page, one with the following in its options:

"modalProduct": {
  ...
  "buttonWithQuantity": true,
  ...
},

and the other with:

"modalProduct": {
  ...
  "buttonWithQuantity": false,
  ...
},

whichever Buy Button's modal I open first will also determine the behavior of the other Buy Button's modal.

i.e., if I open the first product modal first, then close it, then open the second product modal, it will have a button with quantity. If I open the second first, then the first will not.

**Comment by morganmccunn** [comment]
This is expected behaviour. The assumption is that the experience for buy buttons would be the same across all buttons on the same page. For the best user experience, I would encourage you to configure the buttons on the same page with the same behaviours!
