### ISSUE TITLE
Impossible to chain multiple products ?

### ISSUE THREAD

**Issue by Epistol** [Shopify/buy-button-js#698]
We can do ui.createComponent for a product, for a collection, but for multiple products the script just break completely.

**Comment by heart-of-code** [comment]
Can you provide a codepen or a code snippet (with your shopify domain/token/product ids removed)?

**Comment by spencercanner** [comment]
Buy Button JS supports creating a [productSet component](https://shopify.github.io/buy-button-js/#creating-a-component), which allows you to pass in an array of product ids like this:
```
ui.createComponent('productSet', {
  id: [1, 2, 3],
  ...
}
```

**Comment by Epistol** [comment]
Works, thanks ! You should put that in the doc, it's not clear.
