### ISSUE TITLE
Attach products to a custom HTML element

### ISSUE THREAD

**Issue by hapiben** [Shopify/buy-button-js#703]
Hi there,

Just wondering if you can attach/target an HTML element where the products will be rendered? Currently, all products are rendered as direct child of the `body` tag.

```javascript
const ui = ShopifyBuy.UI.init(client)

const options = {
  product: {
    iframe: false,
    buttonDestination: 'modal',
    isButton: true,
    contents: {
      button: false,
      title: false,
      price: false
    }
  },
  modal: {
    iframe: true
  }

ui.createComponent('product', {
  id: 123,
  options
})
```

Cheers!

**Comment by heart-of-code** [comment]
There is a top-level configuration field called `node` that you can use to attach the product to a specific DOM element. 

I don't think it's fully documented but you can see it in this example:
https://shopify.github.io/buy-button-js/#creating-a-component

```
ui.createComponent('product', {
  id: 1234567,
  node: document.getElementById('my-product')
});
```
