### ISSUE TITLE
How to turn variant select box into radio buttons?

### ISSUE THREAD

**Issue by kdavis0424** [Shopify/buy-button-js#743]
I am trying to change the variant select box into being radio buttons, so that I can style them into actually looking like buttons.  I have updated the option template, so that they are displayed as radio buttons.

What is not working is that, when I select a different option, it does not actually change which option is selected.  So, when you hit "add to cart", it always adds the first option no matter what is selected.

How can I get it to correctly select the checked option, or is there a better way to do this?

Here is my code:
<div id='product-component-1604629781277'></div>
<script type="text/javascript">
(function () {
  var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';
  if (window.ShopifyBuy) {
    if (window.ShopifyBuy.UI) {
      ShopifyBuyInit();
    } else {
      loadScript();
    }
  } else {
    loadScript();
  }
  function loadScript() {
    var script = document.createElement('script');
    script.async = true;
    script.src = scriptURL;
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
    script.onload = ShopifyBuyInit;
  }
  function ShopifyBuyInit() {
    var client = ShopifyBuy.buildClient({
      domain: 'wildberries-store.myshopify.com',
      storefrontAccessToken: 'fae781c4b3614788d02e510560a4df2b',
    });
    ShopifyBuy.UI.onReady(client).then(function (ui) {
      ui.createComponent('product', {
iframe: "false",
        id: [product_id],
        node: document.getElementById('product-component-1604629781277'),
        moneyFormat: '%24%7B%7Bamount%7D%7D',
        options: {
  "product": {
iframe: false,
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "calc(25% - 20px)",
          "margin-left": "20px",
          "margin-bottom": "50px"
        }
      },
      "title": {
        "color": "#333333"
      },
      "button": {
        ":hover": {
          "background-color": "#685368"
        },
        "background-color": "#735c74",
        ":focus": {
          "background-color": "#685368"
        },
        "border-radius": "0px"
      },
      "price": {
        "color": "#333333"
      },
      "compareAt": {
        "color": "#333333"
      },
      "unitPrice": {
        "color": "#333333"
      }
    },
    "text": {
      "button": "Add to cart"
    }
  },
  "productSet": {
iframe: false,
    "styles": {
      "products": {
        "@media (min-width: 601px)": {
          "margin-left": "-20px"
        }
      }
    }
  },
  "modalProduct": {
iframe: false,
    "contents": {
      "img": false,
      "imgWithCarousel": true,
      "button": false,
      "buttonWithQuantity": true
    },
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "100%",
          "margin-left": "0px",
          "margin-bottom": "0px"
        }
      },
      "button": {
        ":hover": {
          "background-color": "#685368"
        },
        "background-color": "#735c74",
        ":focus": {
          "background-color": "#685368"
        },
        "border-radius": "0px"
      }
    },
    "text": {
      "button": "Add to cart"
    }
  },
  "cart": {
    "styles": {
      "button": {
        ":hover": {
          "background-color": "#685368"
        },
        "background-color": "#735c74",
        ":focus": {
          "background-color": "#685368"
        },
        "border-radius": "0px"
      }
    },
    "text": {
      "total": "Subtotal",
      "button": "Checkout"
    }
  },
  "toggle": {
    "styles": {
      "toggle": {
        "background-color": "#735c74",
        ":hover": {
          "background-color": "#685368"
        },
        ":focus": {
          "background-color": "#685368"
        }
      }
    }
  },
  "option" : {
    iframe: false,
    "templates": {
      "option": `<div class={{data.classes.option.option}} data-element="option.option">
              <label class="{{data.classes.option.label}} {{#data.onlyOption}}{{data.classes.option.hiddenLabel}}{{/data.onlyOption}}" data-element="option.label">{{data.name}}</label>
              This is customized option template
              <div class="{{data.classes.option.wrapper}}" data-element="option.wrapper">
              {{#data.values}}
              <input {{#selected}}checked{{/selected}} type=radio name=selected_product value="{{name}}">
                  {{name}}
             </input>
              {{/data.values}}
             <svg class="{{data.classes.option.selectIcon}}" data-element="option.selectIcon" viewBox="0 0 24 24"><path d="M21 5.176l-9.086 9.353L3 5.176.686 7.647 12 19.382 23.314 7.647 21 5.176z"></path></svg>
             </div>
         </div>`,
    },
  },
},
      });
    });
  }
})();
</script>

**Comment by spencercanner** [comment]
We've accomplished something similar in this [codepen](https://codepen.io/spencercanner/pen/KbEdVJ). We used the [DOMEvents](http://shopify.github.io/buy-button-js/advanced/#custom-events) object to set up event listeners on elements in the custom template and set the selected variant.

**Comment by kdavis0424** [comment]
Thank you, using DOMEvents worked!

**Comment by bjstafford77** [comment]
@kdavis0424 I know this is closed but I just shot you an email because I'm having a similar issue making this swap and you might be the only person on the internet I can locate that's done it! 😂🥳
