### ISSUE TITLE
Cart Toggle has `display:none` set.

### ISSUE THREAD

**Issue by edalzell** [Shopify/buy-button-js#823]
Hi there, sorry if this is not the correct spot for this.

I'm trying a simple cart/toggle and I have this:

```js
    window.addEventListener('load', (event) => {
        ui.createComponent('cart', {
            id: 'shopify-cart',
            node: document.getElementById('cart'),
            options: {
                cart: {
                  startOpen: false
                }
              }
        });
    });
```

However the toggle component has `display:none` set on it: 
<img width="279" alt="CleanShot 2022-08-17 at 20 42 39@2x" src="https://user-images.githubusercontent.com/6069653/185288436-1fbea739-2fc4-4755-86d9-ef77d76bedbf.png">

Why is it hidden? Is there an easy way to make it visible?

**Comment by ianjosephwilson** [comment]
I don't think it shows the toggle until you add a product to the cart.  I'm sure you are still trying to solve this from August but maybe someone else will find it.

**Comment by edalzell** [comment]
Yup, that's what I realized, thanks!
